/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package distoleos;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.print.PrinterException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import util.conexao;

/**
 *
 * @author Assis Andrade
 */
public class JanelaRelatorio extends javax.swing.JFrame {
    String descricao, codigoSQL, codigoTabela;
    int linhaSelecionada;
    /**
     * Creates new form JanelaPesquisar
     */
    public JanelaRelatorio(String descricaoInformada) {
        initComponents();
        descricao = descricaoInformada;
        preencheTabela();
    }
    
    public void preencheTabela(){
        DefaultTableModel dtm = (DefaultTableModel) this.jTable1.getModel();
        int rowCount = dtm.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }
        conexao.connection().conecta();
        codigoSQL = "SELECT * from producao "
                + "WHERE (Categoria) = '" +descricao+ "'";

        Vector<Vector> dados = new Vector<>();

        try {
            java.sql.ResultSet rs = conexao.connection().executeSQLQuery(codigoSQL);
            while (rs.next()) {
                int codigo = rs.getInt("codigo");
                String Descricao = rs.getString("Descricao");
                String Preco = rs.getString("Preco");
                String ImpostoFederal = rs.getString("ImpostoFederal");
                String ImpostoEstadual = rs.getString("ImpostoEstadual");
                String IPI = rs.getString("IPI");
                String ICMS = rs.getString("ICMS");
                String Frete = rs.getString("Frete");
                String GanhoLivre = rs.getString("GanhoLivre");
                String CustosGerais = rs.getString("CustosGerais");
                String PrecoVenda = rs.getString("PrecoVenda");
                String Categoria = rs.getString("Categoria");

                Vector registroAtual = new Vector();
                registroAtual.add(codigo);
                registroAtual.add(Descricao);
                registroAtual.add(Preco);
                registroAtual.add(ImpostoFederal);
                registroAtual.add(ImpostoEstadual);
                registroAtual.add(IPI);
                registroAtual.add(ICMS);
                registroAtual.add(Frete);
                registroAtual.add(GanhoLivre);
                registroAtual.add(CustosGerais);
                registroAtual.add(PrecoVenda);
                 registroAtual.add(Categoria);

                dados.add(registroAtual);
            }
        } catch (java.sql.SQLException e) {
            throw new java.lang.RuntimeException(e.getMessage());
        }
        
        conexao.connection().desconecta();
        
        for (int i = 0; i < dados.size(); i++) {
            dtm.addRow(dados.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botaoFechar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Precificação JBvox Óleos - Pesquisa");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descricao", "Preco", "IF", "IPI", "IE", "OutrosCustos", "Frete", "GanhoLivre", "CustosGerais", "PrecoVenda", "categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(43);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(70);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(55);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(90);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(55);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(95);
            jTable1.getColumnModel().getColumn(6).setMaxWidth(90);
            jTable1.getColumnModel().getColumn(7).setMaxWidth(55);
            jTable1.getColumnModel().getColumn(8).setMaxWidth(90);
            jTable1.getColumnModel().getColumn(9).setMaxWidth(90);
            jTable1.getColumnModel().getColumn(10).setMaxWidth(90);
            jTable1.getColumnModel().getColumn(11).setMaxWidth(90);
        }

        botaoFechar.setText("Fechar");
        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });

        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoFechar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoFechar)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
        dispose();
    }//GEN-LAST:event_botaoFecharActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            PrintRequestAttributeSet set = new HashPrintRequestAttributeSet();
            set.add(OrientationRequested.LANDSCAPE);
            jTable1.print(JTable.PrintMode.FIT_WIDTH, null, null, true, set, true);
            //jTable1.print();
        } catch (PrinterException ex) {
            Logger.getLogger(JanelaRelatorio.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoFechar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
