/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package distoleos;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import util.conexao;

/**
 *
 * @author Assis Andrade
 */
public class JanelaPesquisar extends javax.swing.JFrame {
    String descricao, codigoSQL, codigoTabela;
    int linhaSelecionada;
    /**
     * Creates new form JanelaPesquisar
     */
    public JanelaPesquisar(String descricaoInformada) {
        initComponents();
        jTable1.addMouseListener(new MouseAdapter() {
        public void mousePressed(MouseEvent me) {
        JTable table =(JTable) me.getSource();
        Point p = me.getPoint();
        int row = table.rowAtPoint(p);
        if (me.getClickCount() == 2) {
            linhaSelecionada = row;
            botaoAlterar.doClick();
        }
    }
});
        descricao = descricaoInformada;
        preencheTabela();
    }
    
    public void preencheTabela(){
        DefaultTableModel dtm = (DefaultTableModel) this.jTable1.getModel();
        int rowCount = dtm.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }
        conexao.connection().conecta();
        System.out.println(descricao);
        codigoSQL = "SELECT * from producao "
                + "WHERE (Descricao) COLLATE UTF8_GENERAL_CI LIKE '%" +descricao+ "%'";

        Vector<Vector> dados = new Vector<>();

        try {
            java.sql.ResultSet rs = conexao.connection().executeSQLQuery(codigoSQL);
            while (rs.next()) {
                int codigo = rs.getInt("codigo");
                String Descricao = rs.getString("Descricao");
                String Preco = rs.getString("Preco");
                String ImpostoFederal = rs.getString("ImpostoFederal");
                String ImpostoEstadual = rs.getString("ImpostoEstadual");
                String IPI = rs.getString("IPI");
                String ICMS = rs.getString("ICMS");
                String Frete = rs.getString("Frete");
                String GanhoLivre = rs.getString("GanhoLivre");
                String CustosGerais = rs.getString("CustosGerais");
                String PrecoVenda = rs.getString("PrecoVenda");

                Vector registroAtual = new Vector();
                registroAtual.add(codigo);
                registroAtual.add(Descricao);
                registroAtual.add(Preco);
                registroAtual.add(ImpostoFederal);
                registroAtual.add(ImpostoEstadual);
                registroAtual.add(IPI);
                registroAtual.add(ICMS);
                registroAtual.add(Frete);
                registroAtual.add(GanhoLivre);
                registroAtual.add(CustosGerais);
                registroAtual.add(PrecoVenda);

                dados.add(registroAtual);
            }
        } catch (java.sql.SQLException e) {
            throw new java.lang.RuntimeException(e.getMessage());
        }
        
        conexao.connection().desconecta();
        
        for (int i = 0; i < dados.size(); i++) {
            dtm.addRow(dados.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botaoFechar = new javax.swing.JButton();
        botaoAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codigo", "Descricao", "Preco", "ImpostoFederal", "IPI", "ImpostoEstadual", "OutrosCustos", "Frete", "GanhoLivre", "CustosGerais", "PrecoVenda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        botaoFechar.setText("Fechar");
        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });

        botaoAlterar.setText("Alterar");
        botaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoFechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoFechar)
                    .addComponent(botaoAlterar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
        dispose();
    }//GEN-LAST:event_botaoFecharActionPerformed

    private void botaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarActionPerformed
        String Descricao = this.jTable1.getValueAt(linhaSelecionada, 1).toString();
        String Preco = this.jTable1.getValueAt(linhaSelecionada, 2).toString();
        String ImpostoFederal = this.jTable1.getValueAt(linhaSelecionada, 3).toString();
        String ImpostoEstadual = this.jTable1.getValueAt(linhaSelecionada, 4).toString();
        String IPI = this.jTable1.getValueAt(linhaSelecionada, 5).toString();
        String ICMS = this.jTable1.getValueAt(linhaSelecionada, 6).toString();
        String Frete = this.jTable1.getValueAt(linhaSelecionada, 7).toString();
        String GanhoLivre = this.jTable1.getValueAt(linhaSelecionada, 8).toString();
        String CustosGerais = this.jTable1.getValueAt(linhaSelecionada, 9).toString();
        String PrecoVenda = this.jTable1.getValueAt(linhaSelecionada, 10).toString();
        String codigo = this.jTable1.getValueAt(linhaSelecionada, 0).toString();
        new AlterarTabela(Descricao, Preco, ImpostoFederal, ImpostoEstadual, IPI, ICMS, Frete, GanhoLivre, CustosGerais, PrecoVenda, codigo).setVisible(true);
        preencheTabela();
    }//GEN-LAST:event_botaoAlterarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterar;
    private javax.swing.JButton botaoFechar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
