/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package distoleos;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import util.conexao;

/**
 *
 * @author Assis Andrade
 */
public class JanelaPesquisar extends javax.swing.JFrame {
    String descricao, codigoSQL;
    /**
     * Creates new form JanelaPesquisar
     */
    public JanelaPesquisar(String descricaoInformada) {
        initComponents();
        descricao = descricaoInformada;
        preencheTabela();
    }
    
    public void preencheTabela(){
        DefaultTableModel dtm = (DefaultTableModel) this.jTable1.getModel();
        int rowCount = dtm.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }
        conexao.connection().conecta();
        System.out.println(descricao);
        codigoSQL = "SELECT * from producao "
                + "WHERE (Descricao) COLLATE UTF8_GENERAL_CI LIKE '%" +descricao+ "%'";

        Vector<Vector> dados = new Vector<>();

        try {
            java.sql.ResultSet rs = conexao.connection().executeSQL(codigoSQL);
            while (rs.next()) {
                int codigo = rs.getInt("codigo");
                String Descricao = rs.getString("Descricao");
                String Preco = rs.getString("Preco");
                String ImpostoFederal = rs.getString("ImpostoFederal");
                String ImpostoEstadual = rs.getString("ImpostoEstadual");
                String IPI = rs.getString("IPI");
                String ICMS = rs.getString("ICMS");
                String Frete = rs.getString("Frete");
                String GanhoLivre = rs.getString("GanhoLivre");
                String CustosGerais = rs.getString("CustosGerais");
                String PrecoVenda = rs.getString("PrecoVenda");

                Vector registroAtual = new Vector();
                registroAtual.add(codigo);
                registroAtual.add(Descricao);
                registroAtual.add(Preco);
                registroAtual.add(ImpostoFederal);
                registroAtual.add(ImpostoEstadual);
                registroAtual.add(IPI);
                registroAtual.add(ICMS);
                registroAtual.add(Frete);
                registroAtual.add(GanhoLivre);
                registroAtual.add(CustosGerais);
                registroAtual.add(PrecoVenda);

                dados.add(registroAtual);
            }
        } catch (java.sql.SQLException e) {
            throw new java.lang.RuntimeException(e.getMessage());
        }
        
        conexao.connection().desconecta();
        
        for (int i = 0; i < dados.size(); i++) {
            dtm.addRow(dados.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codigo", "Descricao", "Preco", "ImpostoFederal", "IPI", "ImpostoEstadual", "ICMS", "Frete", "GanhoLivre", "CustosGerais", "PrecoVenda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
